import pygame
from pygame.math import Vector2

GRID_SIZE = Vector2(30, 30)
TILE_SIZE = Vector2(20, 20)
WINDOW_WIDTH = GRID_SIZE.x * TILE_SIZE.x
WINDOW_HEIGHT = GRID_SIZE.y * TILE_SIZE.y
WINDOW_RECT = pygame.Rect(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT)
INIT_NODE_LENGTH = 2
START_SNAKE_X = 10
START_SNAKE_Y = 10
SNAKE_SPEED = 0.1  # tiles per second
PLAYER_SPEED = 1
PLAYER_COLOR = (0, 200, 200)
SNAKE_HEAD_COLOR = (255, 255, 255)
SNAKE_HEAD_COLOR_2 = (255, 0, 0)
SNAKE_NODE_COLOR = (150, 150, 150)
GAME_SPEED_SCALE = 2
PLAYER_SIZE = TILE_SIZE.x * 2
POWER_UP_SIZE = TILE_SIZE.x
SNAKE_SIZE = TILE_SIZE.x
PLAYER_MOVE_TYPE = 1  # 1: smooth / 2: step by step (snake-like)

# user events
PLAYER_DEAD_EVENT = pygame.USEREVENT + 1
