import pygame
from pygame.math import Vector2

GRID_SIZE = Vector2(30, 30)
TILE_SIZE = Vector2(24, 24)
WINDOW_WIDTH = int(GRID_SIZE.x * TILE_SIZE.x)
WINDOW_HEIGHT = int(GRID_SIZE.y * TILE_SIZE.y)
WINDOW_RECT = pygame.Rect(0, 0, WINDOW_WIDTH, WINDOW_HEIGHT)
INIT_NODE_LENGTH = 5
START_SNAKE_X = 10
START_SNAKE_Y = 10
SNAKE_SPEED = 1.5  # tiles per second
SNAKE_SHOOT_DELAY_TIME = 3
PLAYER_SPEED = 2
SLOW_BULLET_SPEED = 5
PLAYER_COLOR = (0, 200, 200)
SNAKE_HEAD_COLOR = (255, 255, 255)
SNAKE_HEAD_COLOR_2 = (255, 0, 0)
SNAKE_NODE_COLOR = (150, 150, 150)
GRID_COLOR = (50, 50, 50)
GAME_SPEED_SCALE = 2
PLAYER_SIZE = TILE_SIZE.x * 2
POWER_UP_SIZE = TILE_SIZE.x
SNAKE_SIZE = TILE_SIZE.x
PLAYER_MOVE_TYPE = 1  # 1: smooth / 2: step by step (snake-like)
POWER_UP_SPAWN_DELAY_TIME = 5
MAX_POWER_UP_COUNT = 10
SNAKE_SPAWN_DELAY_TIME = 30
MAX_SNAKE_COUNT = 2

# user events
PLAYER_DEAD_EVENT = pygame.USEREVENT + 1
SNAKE_SHOOT_BULLET_EVENT = pygame.USEREVENT + 2
GOT_FRUIT_EVENT = pygame.USEREVENT + 3
